#index:
#    path: /
#    controller: App\Controller\DefaultController::index


home:
    path: /home
    controller: App\Controller\HomeController::home




profilUser:
    path: /profil
    controller: App\Controller\UserController::profil


